package br.com.biblioteca.utils;

public enum TiposMovimentacao {
	CADASTRO_LIVRO,
	EMPRESTIMO,
	DEVOLUCAO,
	RESERVA,
	EXCLUSAO_LIVRO,
	ALTERACAO_LIVRO,
	
	CADASTRO_CLIENTE,
	ALTERACAO_CLIENTE,
	EXCLUSAO_CLIENTE,
	
	CADASTRO_BIBLIOTECARIO,
	ALTERACAO_BIBLIOTECARIO,
	EXCLUSAO_BIBLIOTECARIO,
}
